### ISSUE TITLE
Migrate usages of com.sun.tools.* to provided alternatives

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/lsif-java#84] opened 2021-02-04 14:23 UTC
As per [JEP 396](https://openjdk.java.net/jeps/396), `Tools that use the com.sun.tools.javac.* packages to process source code. Such tools should instead use the javax.tools, javax.lang.model, and com.sun.source.* APIs, available since JDK 6.`

As that package is used in multiple locations, it should be strongly considered to put time into migrating to alternatives which (hopefully) exist in the recommended packages

**Comment by olafurpg** [comment] 2021-02-16 09:49
I think we can close this issue for now. We use `com.sun.source` to access certain necessary APIs like `com.sun.tools.javac.code.Symbol` and `com.sun.tools.javac.tree.JCTree`. We can revisit this issue when we add support for more Java versions.

**Comment by Strum355** [comment] 2021-02-17 22:53
Reopening issue as this is the reason for semanticdb-javac failing with java projects JDK9+ :sweat_smile: `com.sun.tools.javac.code.Kinds` is no longer an enum in JDK9+, with the enum being moved to being an inner class of it. These may further change down the line, so its best we move to supported APIs while we're here :slightly_smiling_face: 

As part of #90 I will migrate to supported public APIs. 

@olafurpg I dont think this will conflict with anything youre working on currently, given youre doing build tool related work, but in the chance that it does, please do go ahead with whats there currently, and I will handle those changes if they arise

**Comment by olafurpg** [comment] 2021-02-18 07:37
Would it make sense to close this issue as a duplicate of #90? It's an implementation detail IMO if we migrate off `com.sun.tools` or if we refactor the code to handle the breaking changes. Judging by the compile errors, I suspect we can work around them with fairly minimal diffs.

**Comment by Strum355** [comment] 2021-02-22 13:58
Ill take some time today to gather how we might approach this. Im leaving out multi-release JARs for now (the one sbt plugin only supports jdk9 :pensive: )

Having another look at this, theres at least one non-obvious change,  [here](https://sourcegraph.com/github.com/sourcegraph/lsif-java/-/blob/semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/GlobalSymbolsCache.java#L100:16) being one, where Scope.Entry has become private. Worst case we make it public with reflection (but I'd really rather not have to introduce that kinda workaround).
The aforementioned enum changing is perhaps a trickier one, we cant guard that with a runtime flag as it will fail compile time regardless of the jdk we use to compile. 

Im personally leaning towards following through with the issue title, I feel itd be the least awkward (Id rather spend time cross-referencing the replacements than messing around with build tooling or version-specific magic), unless you feel strongly about this

**Comment by olafurpg** [comment] 2021-02-22 14:04
It would be great if we can implement the plugin with public APIs. That would be the best outcome so it's worth exploring.

> leaving out multi-release JARs for now (the one sbt plugin only supports jdk9 😔 )

We can ignore multi-release jars for now, it's a future concern.

> Worst case we make it public with reflection (but I'd really rather not have to introduce that kinda workaround).

Using `setAccessible(true)` via reflection would be a fine solution IMO, if it works. I recall that Java 11 is more restrictive with runtime reflection.

**Comment by olafurpg** [comment] 2021-03-01 11:16
Fixed in #91 🔥

**Closed by olafurpg** 2021-03-01 11:16 UTC
Labels: lib/com.sun.source, lsif-java, team/code-intelligence
